// data model goes here
// an array of objects

export const majorArcana = [
    {
        id: 'fool',
        name: 'The Fool',
        image: './assets/major-arcana/fool.png',
        keyWords: 'Key Words: Openness, trust; ready to take a risk; courage to stand your \n ground; freedom, independence; creativity; great potential; possibility to take a quantum leap; listening to the heart\'s voice.',
        interpretation: 'Indications: You are ready for a new beginning, perhaps even a quantum \n leap. Give in, dare to leap, even if fear attempts to hold you back. Trust \n the voice from within your heart.',
        category: 'major-arcana',
    }, 
    {
        id: 'magician',
        name: 'The Magician',
        image: './assets/major-arcana/magician.png',
        keyWords: 'Key Words: Mercury, communication; playful dealings with all possible \n forms of communication; flexibility, brilliance.',
        interpretation: 'Indications: You have at your disposal briliant capabilities which you \n should share with other people. One important task is to find or create \n the proper surroundings for your activities.',
        category: 'major-arcana',
    },  
    {
        id: 'highpriestess',
        name: 'The High Priestess',
        image:'./assets/major-arcana/highpriestess.png',
        keyWords: 'Key Words: Moon; access to intuitive powers; healing, independence, \n inner equilibrium, increased self-confidence.',
        interpretation: 'Indications: You now have access to intuitive powers. Develop \n them more fully. Guard your independence!',
        category: 'major-arcana',
    }, 
    {
        id: 'empress',
        name: 'The Empress',
        image:'./assets/major-arcana/empress.png',
        keyWords: 'Key Words: Venus; beauty; love; motherliness, femininity; wisdom; \n connection between spirit and matter; inner and outer wealth.',
        interpretation: 'Indications: The beauty you see in others which attracts you to them is \n a beauty you can carry within yourself. You are in the process of unfolding \n and evolving your femininity. This may be the right time to work through \n and clarify unresolved mother-conflicts.',
        category: 'major-arcana',
    }, 
    {
        id: 'emperor',
        name: 'The Emperor',
        image:'./assets/major-arcana/emperor.png',
        keyWords: 'Key Words: Aries; pioneer, discoverer, leader, initiator; creative wisdom; \n great leadership qualities; urge for action, adventurousness, new beginnings \n fatherhood, authority.',
        interpretation: 'Indications: This is a propitious moment for a change or a new beginning. \n Trust your own energy and move with it.',
        category: 'major-arcana',
    }, 
    {
        id: 'hierophant',
        name: 'The Hierophant',
        image:'./assets/major-arcana/hierophant.png',
        keyWords: 'Key Words: Taurus; spiritual master, teacher, advisor, initiate, inner \n guide, spiritual father; highest transformation.',
        interpretation: 'Indications: The search for the Self leads you into spiritual realms. This \n card can point to a meeting with a spiritual teacher or master. Be open!',
        category: 'major-arcana',
    }, 
    {
        id: 'lovers',
        name: 'The Lovers',
        image:'./assets/major-arcana/lovers.png',
        keyWords: 'Key Words: Gemini; love, attraction, approaching, connection, union \n of opposites through Love; becoming conscious through relationship.',
        interpretation: 'Indications: Drawing this may indicate a wonderful and exciting \n love relationship. Current relationships either deepen or end. New methods \n for personal growth and integration of your own opposing aspects present \n themselves as you turn toward and interact with a partner or group.',
        category: 'major-arcana',
    }, 
    {
        id: 'chariot',
        name: 'The Chariot',
        image:'./assets/major-arcana/chariot.png',
        keyWords: 'Key Words: Cancer; new beginning, change for the good; introspection \n meditation, spiritual path.',
        interpretation: 'Indications: The oncoming change promises to lead to a positive phase \n of your life. Ready yourself, put your affairs in order, examine the \n possibilities. You will leave much behind.',
        category: 'major-arcana',
    }, 
    {
        id: 'strength',
        name: 'Strength',
        image:'./assets/major-arcana/strength.png',
        keyWords: 'Key Words: Leo; passion; multidimensional creativity, talents; strength; \n integration of animalistic energies; overcoming old fears and conditionings.',
        interpretation: 'Indications: If you are ready to accept all which you find in yourself, \n you will be able to move through everything with deep sensitivity, awareness \n love and understanding.',
        category: 'major-arcana',
    }, 
    {
        id: 'hermit',
        name: 'The Hermit',
        image:'./assets/major-arcana/hermit.png',
        keyWords: 'Key Words: Virgo; finding one\'s own light; going inward; completion, \n harvest; resting in one\'s own center; wise guide.',
        interpretation: 'Indications: Accept your aloneness! Don\'t concern yourself with people \n who don\'t understand you, who would rather see you be a part of the \n herd. If you should meet a wise leader or teacher, join them.',
        category: 'major-arcana',
    }, 
    {
        id: 'wheeloffortune',
        name: 'The Wheel of Fortune',
        image:'./assets/major-arcana/wheeloffortune.png',
        keyWords: 'Key Words: Jupiter; new beginning, expansion, creativity, big break-through; \n self-realization; unexpected fortune.',
        interpretation: 'Indications: If no miracles are happening, something is wrong! You \n stand before the possibility of a great breakthrough! Use the moment!',
        category: 'major-arcana',
    }, 
    {
        id: 'justice',
        name: 'Justice',
        image:'./assets/major-arcana/justice.png',
        keyWords: 'Key Words:  Libra; balance, centering, equilibrium; balancing of opposites; justice.',
        interpretation: 'Indications: Pay attention to what situations in your daily life tend to \n throw you off-balance. Discover the conditions under which you find \n harmony again. Carry this quality with you more and more as you move \n through your daily activities.',
        category: 'major-arcana',
    }, 
    {
        id: 'hangedman',
        name: 'The Hanged Man',
        image:'./assets/major-arcana/hangedman.png',
        keyWords: 'Key Words: congealed; end of a situation or relationship which is stuck; \n letting go, giving up, surrendering; learning to see a new way; the \n necessity of breaking through old behavior patterns.',
        interpretation: 'Indications: It is now possible for you to recognize where you are stuck \n and which areas of your life are congealed rather than flowing. There \n is nothing to do. The mere act of perceiving your daily reality clearly makes \n transformation possible.',
        category: 'major-arcana',
    }, 
    {
        id: 'death',
        name: 'Death',
        image:'./assets/major-arcana/death.png',
        keyWords: 'Key Words: Scorpio; death and resurection; transformation: scorpion, \n snake, eagle, becoming free of old ensnarements; external changes.',
        interpretation: 'Indications: You are now ready to make the necessary changes in your \n life. Accept the pain that may come with the loss of the old.',
        category: 'major-arcana',
    }, 
    {
        id: 'temperance',
        name: 'Temperance',
        image:'./assets/major-arcana/temperance.png',
        keyWords: 'Key Words: Sagittarius; unification of opposites, balance, inner change, \n transformation, alchemy, a quantum leap; creative power.',
        interpretation: 'Indications: The card Temperance is a challenge to look inward. In this phase of \n integrating opposites, the transformation process will not tolerate any \n further impulses or pushes from outside. To find the hidden stone, the \n diamond, you must look within.',
        category: 'major-arcana',
    }, 
    {
        id: 'devil',
        name: 'The Devil',
        image:'./assets/major-arcana/devil.png',
        keyWords: 'Key Words: Capricorn; procreative energy, new vitality; humor; sensuality; \n sexuality; creative energy; individuality.',
        interpretation: 'Indications: There may be people who *demonize* you, make you out \n to be the devil. Meet them with humor and lightness. Accept what Life \n gives you. Keep your feet on the ground!',
        category: 'major-arcana',
    }, 
    {
        id: 'tower',
        name: 'The Tower',
        image:'./assets/major-arcana/tower.png',
        keyWords: 'Key Words: Mars; far-reaching inner transformation; healing; the old is \n destroyed to make room for the new; spiritual renewal; self-knowledge.',
        interpretation: 'Indications: You are in the midst of (or are about to enter into) an \n extremely intensive transformatory process. Whatever is destroyed or \n shaken within you serves to purify you and make room for something \n new. Allow it!',
        category: 'major-arcana',
    }, 
    {
        id: 'star',
        name: 'The Star',
        image:'./assets/major-arcana/star.png',
        keyWords: 'Key Words: Aquarius; inspiration, crystallization, self-recognition, radiating, \n clear vision, trust in the self; connection to the universal intelligence.',
        interpretation: 'Indications: Let your star rise, and stay in contact with the earth. Trust \n your environment and find ways to let others share in it. You will be \n tested and recognized by the fruits you bear.',
        category: 'major-arcana',
    }, 
    {
        id: 'moon',
        name: 'The Moon',
        image:'./assets/major-arcana/moon.png',
        keyWords: 'Key Words: Pisces; final testing; wrong turns, illusion; burning off karma; \n interaction or struggle with the subconscious; threshold to new levels of \n consciousness.',
        interpretation: 'Indications: You have heard the call of the unknown. You are on the \n threshold of new experience. Pay attention now to the voice of your \n heart, and scrutinize calmly and carefully the offers of assistance and \n guidance you may receive.',
        category: 'major-arcana',
    }, 
    {
        id: 'sun',
        name: 'The Sun',
        image:'./assets/major-arcana/sun.png',
        keyWords: 'Key Words: Sun; highly creative energy; awareness; fulfilled love relationship; \n wisdom, spirituality; transformation.',
        interpretation: 'Indications: The fulfillment of your wishes is possible here and now. \n Relax, and give yourself up to the dance. The right partners will find \n each other.',
        category: 'major-arcana',
    }, 
    {
        id: 'judgement',
        name: 'Judgement',
        image:'./assets/major-arcana/judgment.png',
        keyWords: 'Key Words: Highly discriminating or discerning; open to criticism; critical \n self-analysis.',
        interpretation: 'Indications: You are being challenged to drop your *worm\'s eye view* \n to see things from a higher plane. When you have recognized greater \n timespans and other contexts (which are increasingly ready \n to do), you will then tend more and more to observe things in their \n being-ness: to see free from evaluations.',
        category: 'major-arcana',
    }, 
    {
        id: 'world',
        name: 'The World',
        image:'./assets/major-arcana/world.png',
        keyWords: 'Key Words: Saturn; completion, cosmic union; travel liberation from \n bondage; burning off karma.',
        interpretation: 'Indications: It is now possible for you to see things as they really are. \n The stage is set for a new beginning or a favorable completion. The \n events in your life are in harmony with the universe.',
        category: 'major-arcana',
    }, 
];

export const majorArcana2 = [
    {
        id: 'fool2',
        name: 'The Fool',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'magician2',
        name: 'The Magician',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'highpriestess2',
        name: 'The High Priestess',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'empress2',
        name: 'The Empress',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'emperor2',
        name: 'The Emperor',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hierophant2',
        name: 'The Hierophant',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'lovers2',
        name: 'The Lovers',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'chariot2',
        name: 'The Chariot',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'strength2',
        name: 'Strength',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hermit2',
        name: 'The Hermit',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'wheel2',
        name: 'The Wheel of Fortune',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'justice2',
        name: 'Justice',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hangedman2',
        name: 'The Hanged Man',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'death2',
        name: 'Death',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'temperance2',
        name: 'Temperance',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'devil2',
        name: 'The Devil',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'tower2',
        name: 'The Tower',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'star2',
        name: 'The Star',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'moon2',
        name: 'The Moon',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'sun2',
        name: 'The Sun',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'judgment2',
        name: 'Judgment',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'world2',
        name: 'The World',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
];

export const majorArcana3 = [
    {
        id: 'fool3',
        name: 'The Fool',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'magician3',
        name: 'The Magician',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'highpriestess3',
        name: 'The High Priestess',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'empress3',
        name: 'The Empress',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'emperor3',
        name: 'The Emperor',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hierophant3',
        name: 'The Hierophant',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'lovers3',
        name: 'The Lovers',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'chariot3',
        name: 'The Chariot',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'strength3',
        name: 'Strength',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hermit3',
        name: 'The Hermit',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'wheel3',
        name: 'The Wheel of Fortune',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'justice3',
        name: 'Justice',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hangedman3',
        name: 'The Hanged Man',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'death3',
        name: 'Death',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'temperance3',
        name: 'Temperance',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'devil3',
        name: 'The Devil',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'tower3',
        name: 'The Tower',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'star3',
        name: 'The Star',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'moon3',
        name: 'The Moon',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'sun3',
        name: 'The Sun',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'judgment3',
        name: 'Judgment',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'world3',
        name: 'The World',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
];
