// data model goes here
// an array of objects

export const majorArcana = [
    {
        id: 'fool',
        name: 'The Fool',
        image: './assets/major-arcana/fool.png',
        keyWords: 'Key Words: Openness, trust; ready to take a risk; courage to stand your \n ground; freedom, independence; creativity; great potential; possibility to take a quantum leap; listening to the heart\'s voice.',
        interpretation: 'Indications: You are ready for a new beginning, perhaps even a quantum \n leap. Give in, dare to leap, even if fear attempts to hold you back. Trust \n the voice from within your heart.',
            
        category: 'major-arcana',
    }, 
    {
        id: 'magician',
        name: 'The Magician',
        image: './assets/major-arcana/magician.png',
        keyWords: 'Key Words:',
        interpretation: 'text text text',
        category: 'major-arcana',
    },  
    {
        id: 'highpriestess',
        name: 'The High Priestess',
        image:'./assets/major-arcana/highpriestess.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'empress',
        name: 'The Empress',
        image:'./assets/major-arcana/empress.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'emperor',
        name: 'The Emperor',
        image:'./assets/major-arcana/emperor.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hierophant',
        name: 'The Hierophant',
        image:'./assets/major-arcana/hierophant.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'lovers',
        name: 'The Lovers',
        image:'./assets/major-arcana/lovers.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'chariot',
        name: 'The Chariot',
        image:'./assets/major-arcana/chariot.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'strength',
        name: 'Strength',
        image:'./assets/major-arcana/strength.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hermit',
        name: 'The Hermit',
        image:'./assets/major-arcana/hermit.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'wheeloffortune',
        name: 'The Wheel of Fortune',
        image:'./assets/major-arcana/wheeloffortune.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'justice',
        name: 'Justice',
        image:'./assets/major-arcana/justice.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hangedman',
        name: 'The Hanged Man',
        image:'./assets/major-arcana/hangedman.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'death',
        name: 'Death',
        image:'./assets/major-arcana/death.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'temperance',
        name: 'Temperance',
        image:'./assets/major-arcana/temperance.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'devil',
        name: 'The Devil',
        image:'./assets/major-arcana/devil.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'tower',
        name: 'The Tower',
        image:'./assets/major-arcana/tower.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'star',
        name: 'The Star',
        image:'./assets/major-arcana/star.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'moon',
        name: 'The Moon',
        image:'./assets/major-arcana/moon.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'sun',
        name: 'The Sun',
        image:'./assets/major-arcana/sun.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'judgement',
        name: 'Judgement',
        image:'./assets/major-arcana/judgment.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'world',
        name: 'The World',
        image:'./assets/major-arcana/world.png',
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
];

export const majorArcana2 = [
    {
        id: 'fool2',
        name: 'The Fool',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'magician2',
        name: 'The Magician',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'highpriestess2',
        name: 'The High Priestess',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'empress2',
        name: 'The Empress',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'emperor2',
        name: 'The Emperor',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hierophant2',
        name: 'The Hierophant',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'lovers2',
        name: 'The Lovers',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'chariot2',
        name: 'The Chariot',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'strength2',
        name: 'Strength',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hermit2',
        name: 'The Hermit',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'wheel2',
        name: 'The Wheel of Fortune',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'justice2',
        name: 'Justice',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hangedman2',
        name: 'The Hanged Man',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'death2',
        name: 'Death',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'temperance2',
        name: 'Temperance',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'devil2',
        name: 'The Devil',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'tower2',
        name: 'The Tower',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'star2',
        name: 'The Star',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'moon2',
        name: 'The Moon',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'sun2',
        name: 'The Sun',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'judgment2',
        name: 'Judgment',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'world2',
        name: 'The World',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
];

export const majorArcana3 = [
    {
        id: 'fool3',
        name: 'The Fool',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'magician3',
        name: 'The Magician',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'highpriestess3',
        name: 'The High Priestess',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'empress3',
        name: 'The Empress',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'emperor3',
        name: 'The Emperor',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hierophant3',
        name: 'The Hierophant',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'lovers3',
        name: 'The Lovers',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'chariot3',
        name: 'The Chariot',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'strength3',
        name: 'Strength',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hermit3',
        name: 'The Hermit',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'wheel3',
        name: 'The Wheel of Fortune',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'justice3',
        name: 'Justice',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hangedman3',
        name: 'The Hanged Man',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'death3',
        name: 'Death',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'temperance3',
        name: 'Temperance',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'devil3',
        name: 'The Devil',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'tower3',
        name: 'The Tower',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'star3',
        name: 'The Star',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'moon3',
        name: 'The Moon',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'sun3',
        name: 'The Sun',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'judgment3',
        name: 'Judgment',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'world3',
        name: 'The World',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
];
