// data model goes here
// an array of objects

export const majorArcana = [
    {
        id: 'fool',
        name: 'The Fool',
        //image: url('...'),
        keyWords: 'Key Words: openness, trust; ready to take a risk; courage to stand your ground; \n freedom, independence; creativity; ',
        interpretation: 'Key Words',
            
        category: 'major-arcana',
    }, 
    {
        id: 'magician',
        name: 'The Magician',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    },  
    {
        id: 'highPriestess',
        name: 'The High Priestess',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'empress',
        name: 'The Empress',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'emperor',
        name: 'The Emperor',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hierophant',
        name: 'The Hierophant',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'lovers',
        name: 'The Lovers',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'chariot',
        name: 'The Chariot',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'strength',
        name: 'Strength',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hermit',
        name: 'The Hermit',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'wheel',
        name: 'The Wheel of Fortune',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'justice',
        name: 'Justice',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hangedMan',
        name: 'The Hanged Man',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'death',
        name: 'Death',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'temperance',
        name: 'Temperance',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'devil',
        name: 'The Devil',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'tower',
        name: 'The Tower',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'star',
        name: 'The Star',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'moon',
        name: 'The Moon',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'sun',
        name: 'The Sun',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'judgment',
        name: 'Judgment',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'world',
        name: 'The World',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
];

export const majorArcana2 = [
    {
        id: 'fool2',
        name: 'The Fool',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'magician2',
        name: 'The Magician',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'highPriestess2',
        name: 'The High Priestess',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'empress2',
        name: 'The Empress',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'emperor2',
        name: 'The Emperor',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hierophant2',
        name: 'The Hierophant',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'lovers2',
        name: 'The Lovers',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'chariot2',
        name: 'The Chariot',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'strength2',
        name: 'Strength',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hermit2',
        name: 'The Hermit',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'wheel2',
        name: 'The Wheel of Fortune',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'justice2',
        name: 'Justice',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hangedMan2',
        name: 'The Hanged Man',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'death2',
        name: 'Death',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'temperance2',
        name: 'Temperance',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'devil2',
        name: 'The Devil',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'tower2',
        name: 'The Tower',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'star2',
        name: 'The Star',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'moon2',
        name: 'The Moon',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'sun2',
        name: 'The Sun',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'judgment2',
        name: 'Judgment',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'world2',
        name: 'The World',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
];

export const majorArcana3 = [
    {
        id: 'fool3',
        name: 'The Fool',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'magician3',
        name: 'The Magician',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'highPriestess3',
        name: 'The High Priestess',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'empress3',
        name: 'The Empress',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'emperor3',
        name: 'The Emperor',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hierophant3',
        name: 'The Hierophant',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'lovers3',
        name: 'The Lovers',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'chariot3',
        name: 'The Chariot',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'strength3',
        name: 'Strength',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hermit3',
        name: 'The Hermit',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'wheel3',
        name: 'The Wheel of Fortune',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'justice3',
        name: 'Justice',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'hangedMan3',
        name: 'The Hanged Man',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'death3',
        name: 'Death',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'temperance3',
        name: 'Temperance',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'devil3',
        name: 'The Devil',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'tower3',
        name: 'The Tower',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'star3',
        name: 'The Star',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'moon3',
        name: 'The Moon',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'sun3',
        name: 'The Sun',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'judgment3',
        name: 'Judgment',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
    {
        id: 'world3',
        name: 'The World',
        //image: url('...'),
        keyWords: 'text text text',
        interpretation: 'text text text',
        category: 'major-arcana',
    }, 
];
